name: Docs

on:
  push:
    branches:
    - master

jobs:
  docs:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
    - name: Install
      run: |
        pip install -e .[dev]
    - name: Build documentation
      run: |
        make html
      working-directory: ./docs
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs/_build/html
